spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: uber0815!
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
